### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by JordanYu4** [JordanYu4/Mise#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by JordanYu4** [comment]
@evhumphrey I believe user auth is good to go. The CSS is buggy, but I'm going to move on to the next MVP and polish CSS later if that's alright.

**Comment by evhumphrey** [comment]
@JordanYu4 Awesome! What is the link to your heroku app?

**Comment by JordanYu4** [comment]
@evhumphrey I added the heroku link to the wiki index, thanks for the reminder. I'm thinking of changing the app name, which is why the header is "Gylio" instead of "Mise."
